def map_live_team_name(raw_name, team_name_map):
    normalized = normalize_team_name(raw_name)
    for original_name, mapped_name in team_name_map.items():
        if normalize_team_name(original_name) == normalized:
            return mapped_name
    return raw_name

team_name_map = {
     # Premier League (E0)
    "AFC Bournemouth":"Bournemouth",
    "Arsenal FC": "Arsenal",
    "Aston Villa FC": "Aston Villa",
    "Brentford FC": "Brentford",
    "Brighton & Hove Albion FC": "Brighton",
    "Burnley FC": "Burnley",
    "Chelsea FC": "Chelsea",
    "Crystal Palace FC": "Crystal Palace",
    "Everton FC": "Everton",
    "Fulham FC": "Fulham",
    "Liverpool FC": "Liverpool",
    "Luton Town FC": "Luton",
    "Manchester City FC": "Man City",
    "Manchester United FC": "Man United",
    "Newcastle United FC": "Newcastle",
    "Nottingham Forest FC": "Nottm Forest",
    "Sheffield United FC": "Sheffield United",
    "Tottenham Hotspur FC": "Tottenham",
    "West Ham United FC": "West Ham",
    "Wolverhampton Wanderers FC": "Wolves",
    "Southampton FC":"Southampton",
    "Ipswich Town FC":"Ipswich",
    "Leicester City FC":"Leicester",


    # La Liga (SP1)
    "Real Madrid CF":"Real Madrid",
    "FC Barcelona":"Barcelona",
    "Espanyol": "Espanol",
    "Girona FC": "Girona",
    "RC Celta de Vigo": "Celta",
    "Real Betis Balompié": "Betis",
    "Valencia CF":"Valencia",
    "Getafe CF"	:"Getafe",
    "Sevilla FC":"Sevilla",
    "Villarreal CF":"Villarreal",
    "UD Las Palmas":"Las Palmas",
    "Club Atlético de Madrid":"Ath Madrid",
    "RCD Mallorca":"Mallorca",
    "Real Valladolid CF":"Valladolid",
    "Rayo Vallecano de Madrid":"Vallecano",
    "Real Sociedad de Fútbol":"Sociedad",
    'RCD Espanyol de Barcelona':'Espanol',
    "CD Leganés":"Leganes",
    "Athletic Club":"Ath Bilbao",
    

    # Serie A (I1)
    "AC Milan": "Milan",
    "Inter Milan": "Inter",
    "FC Internazionale Milano": "Inter",
    "SSC Napoli": "Napoli",
    "AS Roma": "Roma",
    "SS Lazio": "Lazio",
    "Juventus FC": "Juventus",
    "Atalanta BC": "Atalanta",
    "Torino FC": "Torino",
    "Fiorentina": "Fiorentina",
    "ACF Fiorentina": "Fiorentina",
    "Udinese Calcio": "Udinese",
    "Bologna FC 1909": "Bologna",
    "Hellas Verona FC": "Verona",
    "US Lecce": "Lecce",
    "Empoli FC": "Empoli",
    "Genoa CFC": "Genoa",
    "Cagliari Calcio": "Cagliari",
    "Como 1907": "Como",
    "AC Monza": "Monza",
    "Parma Calcio 1913": "Parma",
    "Venezia FC":"Venezia",
    "Deportivo Alavés":"Alaves",
    "CA Osasuna":"Osasuna",

    # Ligue 1 (F1)
    "Paris Saint-Germain FC": "Paris SG",
    "Olympique de Marseille": "Marseille",
    "Olympique Lyonnais": "Lyon",
    "AS Monaco FC": "Monaco",
    "Lille OSC": "Lille",
    "OGC Nice": "Nice",
    "Stade Rennais FC 1901": "Rennes",
    "RC Strasbourg Alsace": "Strasbourg",
    "FC Nantes": "Nantes",
    "Stade Brestois 29": "Brest",
    "Toulouse FC": "Toulouse",
    "Montpellier HSC": "Montpellier",
    "Le Havre AC": "Le Havre",
    "Stade de Reims": "Reims",
    "Clermont Foot 63": "Clermont",
    "Metz": "Metz",
    "RC Lens": "Lens",
    "Angers SCO": "Angers",
    "AJ Auxerre": "Auxerre",
    "AS Saint-Étienne": "St Etienne",
    "Racing Club de Lens":"Lens",

    #Bundesliga
    "Bayer 04 Leverkusen":"Leverkusen",
    "FC Augsburg":"Augsburg",
    "FC St. Pauli 1910":"St Pauli",

    # OpenFootball Süper Lig feed
    "Fenerbahçe": "Fenerbahce",
    "Beşiktaş": "Besiktas",
    "Çaykur Rizespor": "Rizespor",
    "Gençlerbirliği": "Genclerbirligi",
    "Fatih Karagümrük": "Karagumruk",
    "Kasimpaşa SK": "Kasimpasa",
    "Kasımpaşa SK": "Kasimpasa",
    "Istanbul Başakşehir": "Buyuksehyr",
    "Istanbul Basaksehir": "Buyuksehyr",
    "İstanbul Başakşehir": "Buyuksehyr",
    "Göztepe": "Goztep",
    "Gaziantep FK": "Gaziantep",
    "Eyüpspor": "Eyupspor",
    "SV Werder Bremen":"Werder Bremen",
    "1. FC Heidenheim 1846":"Heidenheim",
    "1 FC Heidenheim 1846":"Heidenheim",
    "TSG 1899 Hoffenheim": "Hoffenheim",
    "FC St Pauli": "St Pauli",
    "1 FC Heidenheim": "Heidenheim",
    "VfL Bochum 1848": "Bochum",
    'Borussia Mönchengladbach': "MGladbach",
    'Borussia Dortmund':"Dortmund",
    "Bayer Leverkusen":"Leverkusen",
    'Eintracht Frankfurt':"Ein Frankfurt",
     'VfB Stuttgart':"Stuttgart",
    "Borussia Monchengladbach": "MGladbach",
    "Bayer Leverkusen": "Leverkusen", 
    "1. FSV Mainz 05": "Mainz",
    "Mainz 05": "Mainz",
    "SC Freiburg": "Freiburg",
    "VfL Wolfsburg": "Wolfsburg",
    "VfB Stuttgart": "Stuttgart", 
    "FC Bayern München":"Bayern Munich",
    "1. FC Union Berlin":"Union Berlin",
    "1 FC Union Berlin":"Union Berlin",
    "TSG Hoffenheim": "Hoffenheim",
    "FC St Pauli": "St Pauli",
    "1 FC Heidenheim": "Heidenheim",
    "VfL Bochum": "Bochum",
    'Borussia Mönchengladbach': "MGladbach",
    'Borussia Dortmund':"Dortmund",
    "Bayer Leverkusen":"Leverkusen",
    'Eintracht Frankfurt':"Ein Frankfurt",
     'VfB Stuttgart':"Stuttgart",
    "Borussia Monchengladbach": "MGladbach",
    "Bayer Leverkusen": "Leverkusen", 
    "FSV Mainz 05": "Mainz 05",
    "SC Freiburg": "Freiburg",
    "VfL Wolfsburg": "Wolfsburg",
    "VfB Stuttgart": "Stuttgart",
    "1. FC Heidenheim":"Heidenheim",
    "Mainz 05":"Mainz",
    "FC St. Pauli":"St Pauli",
    "Bayer 04 Leverkusen":"Leverkusen",
    "FC Augsburg":"Augsburg",
    "FC St. Pauli 1910":"St Pauli",
    

    # Premier League
    "Manchester United": "Man United",
    "Manchester City": "Man City",
    "Brighton and Hove Albion": "Brighton",
    "Tottenham Hotspur": "Tottenham",
    "West Ham United": "West Ham",
    "Wolverhampton Wanderers": "Wolves",
    "Leicester City": "Leicester",
    "Nottingham Forest": "Nottm Forest",
    "Newcastle United": "Newcastle",
    "Sevilla FC":"Sevilla",
    "Ipswich Town":"Ipswich",

    # La Liga
    "Atlético Madrid": "Ath Madrid",
    "Athletic Bilbao": "Ath Bilbao",
    "RC Lens": "Lens",
    "Rayo Vallecano": "Vallecano",
    "Real Sociedad": "Sociedad",
    "Real Betis": "Betis",
    "CA Osasuna": "Osasuna",
    "Leganés": "Leganes",
    "Celta Vigo": "Celta",
    "Espanyol": "Espanol",
    "Alavés":"Alaves",

    # Serie A
    "AC Milan": "Milan",
    "Inter Milan": "Inter",
    "AS Roma": "Roma",
    "Atalanta BC": "Atalanta",
    "Hellas Verona": "Verona",
    "AS Monaco": "Monaco",  # Monaco aslında Ligue 1 ama API'de İtalya olabilir
    "Paris Saint Germain": "Paris SG",

    # Ligue 1
    "Saint Etienne": "St Etienne",
    "Stade de Reims": "Reims",
    "Racing Club de Lens":"Lens",
}
def normalize_team_name(name):
    cleaned_name = (
        name.replace(".", "")
            .replace("’", "'")
            .replace("`", "'")
            .replace("´", "'")
            .replace("İ", "I")
            .replace("ı", "i")
            .strip()
    )
    return team_name_map.get(cleaned_name, cleaned_name)
